### ISSUE TITLE
[Bug]: Cant shoot arrows

### ISSUE THREAD

**Issue by rainysux** [Fuzss/puzzleslib#63] opened 2023-08-12 05:44 UTC
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.19-1.20.1

### Notes (Required)

Unable to shoot arrows after update. Not much to be said :P

**Comment by Fuzss** [comment] 2023-08-12 08:16
Please upload your latest.log file. I cannot reproduce the issue with just Puzzles Lib, so another mod must be involved.

**Comment by Aninuscsalas** [comment] 2023-08-12 09:43
Same here. This issue isn't present when using the mods alone.
I was only able to reproduce the bug in my modpack.
I cant see anything relevant in the logs, but they might be helpful 

- Puzzles Lib 8.0.15 (Without Illager Invasion) : https://mclo.gs/oXwbL8u (Bows, tridents work )
- Puzzles Lib 8.0.19 : https://mclo.gs/fMZrrBD (Bows, tridents don't work )

**Comment by Fuzss** [comment] 2023-08-12 13:45
Thank you! The issue has just been fixed in the latest version of Puzzles Lib. Will take a few minutes to become available on CurseForge.

**Closed by Fuzss** 2023-08-12 13:45 UTC
Labels: bug
