### ISSUE TITLE
[Bug]: Single player worlds unable to join

### ISSUE THREAD

**Issue by Zelioth** [Fuzss/puzzleslib#15] opened 2022-11-02 05:18 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.3.12

### Notes (Required)

I am the creator/Dev of Friends United for Minecraft Version 1.19.2. we are running the Forge version 43.1.47. I am testing the pack looking for a memory leak, a major one in this process this error kicked me from a single player world generation and in the debug referenced the kick was from Puzzle Lib. I wanted to share so you may see this issue and may have the ability to fix it or tell me what caused it so others never have it. Thank you :D 

Here are the logs for that instance. the issue is the LAST reported. 

[latest.log](https://github.com/Fuzss/puzzleslib/files/9916536/latest.log)
[debug.log](https://github.com/Fuzss/puzzleslib/files/9916537/debug.log)

**Comment by Fuzss** [comment] 2022-11-02 06:42
The issue is in EasyAnvils. It‘s also not really an issue, it‘s just that a config value is being used before the config is loaded, in such a case the default config value is simply used. I print the full stacktrace to the log to be better able to diagnose the issue, but it‘s really nothing serious.

**Comment by Zelioth** [comment] 2022-11-02 07:08
But would this issue cause a single player world kick?

**Comment by Fuzss** [comment] 2022-11-02 07:21
No definitely not. 
Your actual error is a little bit above that:

[02Nov2022 00:12:03.660] [Netty Server IO #1/ERROR] [net.minecraft.network.Connection/]: Received class net.minecraft.network.protocol.game.ClientboundDisconnectPacket that couldn't be processed
java.lang.ClassCastException: class net.minecraft.server.network.ServerGamePacketListenerImpl cannot be cast to class net.minecraft.network.protocol.game.ClientGamePacketListener (net.minecraft.server.network.ServerGamePacketListenerImpl and net.minecraft.network.protocol.game.ClientGamePacketListener are in module minecraft@1.19.2 of loader 'TRANSFORMER' @780ee3ad)

Looks like a mod maybe is sending a packet to the wrong side. You can usually just do a binary search in such a case, there is usually nothing in the stacktrace hinting at the faulty mod for issues on the network thread.

**Comment by Fuzss** [comment] 2022-12-05 13:25
Closing this now as it seems to be unrelated to Puzzles Lib.

**Closed by Fuzss** 2022-12-05 13:25 UTC
Labels: bug
