### ISSUE TITLE
[Bug]: Some items of the Create fabric mod won't render

### ISSUE THREAD

**Issue by mxKeaton** [Fuzss/puzzleslib#70] opened 2023-09-18 19:44 UTC
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

Recent 4 (tested 8.0.2 - 8.0.4), possibly more

### Notes (Required)

While Puzzles Lib is installed, some items of the Create fabric mod won't render. Sometimes part of them, but most often they are completely invisible. Removing puzzleslib fixes the issue immediatly.
![image](https://github.com/Fuzss/puzzleslib/assets/83590708/3e1400cc-4289-45f5-afcc-f18439f17aac)

There are a lot create rendering errors in the log, maybe they help figuring it out.
(the log features various puzzleslib mods, but even without them the issue occurs)

Sadly can not use over 10 mods because I will have to get rid of puzzleslib
Additional possible mods related: sodium 0.4.10+build.27 & indium 1.0.21+mc1.20.1

### latest.log (Optional)

https://mclo.gs/RHHsRD0

**Comment by Fuzss** [comment] 2023-10-15 15:37
Is this still an issue on the latest versions of Puzzles Lib and Create?

Did some testing myself and didn't run into any issue. Also not able to reproduce the errors from your log.

**Comment by Fuzss** [comment] 2023-10-26 14:50
I was able to reproduce the error that was logged for you now. Rendering the items worked still fine though.
I always got it related to the Continuity mod in some combination, like with Better End, even without Puzzles Lib installed.
So closing this now, as Puzzles Lib doesn't seem to be at fault.

**Closed by Fuzss** 2023-10-26 14:50 UTC
Labels: bug
