### ISSUE TITLE
[Crash]: 1.19.2 fabric crash

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Fuzss/puzzleslib#13] opened 2022-09-26 03:04 UTC
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.3.4

### Notes (Required)

Run the mods listed as active in the log. <If need be, I can go through and figure out the conflicting mods myself- Although this seems to be more a blanket issue, as it seems to happen with so many different mods>

Without not enough crashes, It just crashes entirely, With the mod though, it just spams my logs with crash reports and slows down the game considerably

### Crash Report (Required)

https://paste.ee/p/jECFM

**Comment by Fuzss** [comment] 2022-10-04 11:35
This is a conflict between Polymer and Air Hop, although from the log you provided this isn‘t the cause of any crash. 

The Air Hop enchantment is configurable, but the config values come from a server config which is world specific (like data packs). Polymer causes a call to the enchantment before the server config is loaded, therefore the log spam. 
But the system is designed to only print to the log, no actual exception is thrown. The default value will be used in such a case.

**Comment by Footage2-Amply-Pounce** [comment] 2022-10-04 11:40
Not the original poster, but it's not just Air Hop, the issue seems to happen with other mods that rely on Puzzles Lib too. And I also at first thought it could be an issue between them and Polymer, but I couldn't reproduce it with just these mods. I ended up just giving up and using Log Begone to remove the log spam. In my case, I never experienced a crash, but logs were getting huge in size, causing PolyMC to freeze.

**Comment by Footage2-Amply-Pounce** [comment] 2022-10-04 12:34
Seems to be Easy Anvils. I couldn't upload the full log because it causes github to crash lol: https://gist.github.com/Footage2-Amply-Pounce/509705201c498a754b48ad01decdc8b6. It's the same exact thing repeating over and over again multiple times a second. Removed Easy Anvils just to make sure no other mods cause this and it seems to be the case.

The log is from Quilt, but it's the same on Fabric. And again, I couldn't reproduce this with just your mods + Polymer, I spent a few hours binary searching, but couldn't find the exact mods needed.

**Comment by Fuzss** [comment] 2022-10-04 14:08
The spam should be fixed in Puzzles v4.3.9. Can you confirm that?

**Comment by Footage2-Amply-Pounce** [comment] 2022-10-04 14:20
Yep, the error shows only once now. Thank you.

**Comment by Fuzss** [comment] 2022-10-15 14:03
Great, so I'll close this.

**Closed by Fuzss** 2022-10-15 14:03 UTC
Labels: bug
