### ISSUE TITLE
[Crash]: the printer crash

### ISSUE THREAD

**Issue by Rogenar** [Fuzss/puzzleslib#30] opened 2023-03-25 17:47 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

5.0.11

### Notes (Required)

I talked to the printer mod maker. It was causing the game to crash when copying an item. He said the problem was in Puzzleslib mode. 
[latest.log](https://github.com/Fuzss/puzzleslib/files/11069669/latest.log)
[rei.log](https://github.com/Fuzss/puzzleslib/files/11069670/rei.log)
[rei-issues.log](https://github.com/Fuzss/puzzleslib/files/11069671/rei-issues.log)
[crash-2023-03-25_20.43.04-client.txt](https://github.com/Fuzss/puzzleslib/files/11069672/crash-2023-03-25_20.43.04-client.txt)

### Crash Report (Required)

[crash-2023-03-25_20.43.04-client.txt](https://github.com/Fuzss/puzzleslib/files/11069672/crash-2023-03-25_20.43.04-client.txt)

### latest.log (Optional)

[latest.log](https://github.com/Fuzss/puzzleslib/files/11069669/latest.log)

**Comment by Fuzss** [comment] 2023-03-25 18:26
Thanks for the report, the cause of your crash report is not related to Puzzles Lib. There was indeed an issue with Puzzles Lib previously as indicated [here](https://github.com/acikek/the-printer/issues/6), which is fixed in the current version though.

**Closed by Fuzss** 2023-03-25 18:26 UTC
Labels: bug

**Comment by acikek** [comment] 2023-03-25 21:33
Note: this was not the crash I was referring to [in this issue](https://github.com/acikek/the-printer/issues/6). This user said they had the same error with the new PuzzlesLib version - I thought they were talking about the last error they had provided, which was indeed fixed in this version, but it was actually something entirely different (they didn't specify). Sorry for the inconvenience.

**Comment by Fuzss** [comment] 2023-03-25 21:39
No worries, already came to that conclusion. Thanks for the heads up!

**Comment by Rogenar** [comment] 2023-03-25 21:42
So what is the solution to this problem?

**Comment by Fuzss** [comment] 2023-03-25 21:55
https://github.com/acikek/the-printer/issues/6#issuecomment-1483927927
