### ISSUE TITLE
[Crash]: Puzzles Lib Crash on Gathering Possibles Animal Spawns List

### ISSUE THREAD

**Issue by serioos** [Fuzss/puzzleslib#108] opened 2024-04-09 13:13 UTC
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

PuzzlesLib-v8.1.18-1.20.1-Forge

### Other Mods Involved (Required)

Yes

### Notes (Required)

I generated a world and it crashes just walking around. I was working fine until now. All I did was add Essential mod to be able to play with my friend and now that I made a new world, it crashes. It crashed twice now. Here are the logs:

![2024-04-09_16 31 19](https://github.com/Fuzss/puzzleslib/assets/93765296/23dc3c74-0b78-4028-aaa9-70696572a302)

Crash logs:

[crash-2024-04-09_16.27.45-server.txt](https://github.com/Fuzss/puzzleslib/files/14918916/crash-2024-04-09_16.27.45-server.txt)
[crash-2024-04-09_16.31.10-server.txt](https://github.com/Fuzss/puzzleslib/files/14918917/crash-2024-04-09_16.31.10-server.txt)

### latest.log (Required)

https://github.com/Fuzss/puzzleslib/files/14918942/latest.log

**Comment by serioos** [comment] 2024-04-09 13:40
I removed Respawning Animals mod and generated a new world. So far so good, no crash. I'll let you know if anything changes after playing a while longer.

**Comment by Fuzss** [comment] 2024-04-09 13:49
Please test this custom version of Puzzles Lib along with Respawning Animals and submit the new  crash report, it should include more details.

https://cdn.discordapp.com/attachments/917550806922846299/1227253878752411720/PuzzlesLib-v8.1.19.882-1.20.1-Forge.jar?ex=6627bc3d&is=6615473d&hm=1e8f889257ccde268b88d7f1613390d335854332121c34e6f22f8a8af96413e3&

**Comment by serioos** [comment] 2024-04-09 19:43
I did it. Here's crash log and the latest log:

[crash-2024-04-09_23.11.30-server.txt](https://github.com/Fuzss/puzzleslib/files/14923192/crash-2024-04-09_23.11.30-server.txt)

[latest.log](https://github.com/Fuzss/puzzleslib/files/14923195/latest.log)

**Comment by serioos** [comment] 2024-04-11 09:36
Here:

[crash-2024-04-11_13.04.10-server.txt](https://github.com/Fuzss/puzzleslib/files/14944303/crash-2024-04-11_13.04.10-server.txt)

[latest.log](https://github.com/Fuzss/puzzleslib/files/14944305/latest.log)

**Comment by Fuzss** [comment] 2024-04-11 10:37
Thanks, so this tells us the crash is happening when trying to spawn a mob in the savannah plateau biome, specifically the Friends&Foes mauler is causing issues (although this is unlikely to be related to Friends&Foes directly).

Unfortunately there isn't much more I can get from this.

So the next question would be can you reproduce the issue with just Respawning Animals + Friends&Foes (+dependencies)?

If not it's maybe caused by some optimization mod, a binary search (removing half of the mods until the offender is found) will be necessary.

Thanks for helping out with this, can't resolve it on my own unfortunately as I'm unable to reproduce the issue.

**Comment by serioos** [comment] 2024-04-14 17:05
Now I only installed Respawning Animals and Friends&Foes mods, and tested them a bit. Went to Savanna Plateau and spawned mauler and flied around a bit. So far, there hasn't been a crash. I'll keep testing some more. I'll let you know if I crash.

**Comment by Faboslav** [comment] 2024-05-01 11:32
@serioos Is there any update on this? As on my side (Friends&Foes) i have no idea what to do with this issue.

**Comment by serioos** [comment] 2024-05-01 11:36
@Faboslav I guess we can just close this one for now. I do not know what to do about it either without Friends&Foes developer. They haven't visited yet. Sorry about bothering you, and thanks for the patience.

**Comment by Fuzss** [comment] 2024-05-01 11:42
This issue seems to not be possible to reproduce with just Friends&Foes and Respawning Animals, so I have to assume another mod in your setup is at fault. 
It would be very helpful if you could start removing mods from your mod pack until the issue goes away to find the one responsible so I can work on a fix.

**Comment by serioos** [comment] 2024-05-01 11:44
I also think this was caused by another unknown mod in my very long mod list. I cannot find which one it is though, because testing this and getting the error actually takes time and I have to fly around for quite a while until I get the crash which makes removing mods and testing really cumbersome.

And my mod list has changed a lot since then. I've removed a lot of mod, but it's still a big mod pack. I'm going to install respawning animals again and test it again now with the new mod pack.

**Comment by Fuzss** [comment] 2024-05-01 12:04
That would be a great start, thank you.

**Comment by serioos** [comment] 2024-05-01 12:24
Here's my modpack along with the save file for testing. I hope it helps you both:

[Chicken-1.0.zip](https://github.com/Fuzss/puzzleslib/files/15176922/Chicken-1.0.zip)

If you don't get the crash immediately like me, the mob or thing that caused it might have despawned. You may need to hang around there for a bit?

**Comment by serioos** [comment] 2024-05-09 14:03
@Fuzss 

Good news! I finally found the mod that is causing the crash when I add it to the combination of respawning animals, regions unexplored, terralith, puzzleslib, and friends and foes!

It's ModernFix of all mods! I didn't expect it at all, and thought that was a pretty safe mod! But when I add it, it gives the null exception error for the possible respawnable animals crash. And the crash consistently happens in the Baobab_savanna Biome from regions unxplored.

Here are the crash logs I got with only these mods on:

[crash-2024-05-09_17.29.23-server.txt](https://github.com/Fuzss/puzzleslib/files/15263226/crash-2024-05-09_17.29.23-server.txt)

[latest.log](https://github.com/Fuzss/puzzleslib/files/15263227/latest.log)

**Comment by Fuzss** [comment] 2024-05-09 14:11
Thank you so much for investing so much time on finding the conflict! This helps a lot, will hopefully be able to fix this soon then.

**Comment by Fuzss** [comment] 2024-05-09 14:46
The issue should be fixed. Please try this custom version of Puzzles Lib, to check that it no longer crashes for you.

https://cdn.discordapp.com/attachments/917550806922846299/1238139867544817664/PuzzlesLib-v8.1.20.894-1.20.1-Forge.jar?ex=663e331b&is=663ce19b&hm=7d2ef23f30fb13ded6c3227a1b766e4e9d0b378726937a8a7a67f148a5e8ebc7&

**Comment by serioos** [comment] 2024-05-09 15:36
Wow, you're fast! I'm very impressed.

Look! I tried it and it doesn't crash anymore! Here's our #1 suspect, MaulMaul!

![2024-05-09_18 45 13](https://github.com/Fuzss/puzzleslib/assets/93765296/7a60d38d-4605-4740-ae39-8c07546ed7ba)

I tried it with my whole modpack and it works there too with no crashes.

Thank you so much for your hard work as well. ❤️

**Comment by Fuzss** [comment] 2024-05-09 17:51
New version is public now.

**Closed by Fuzss** 2024-05-09 17:51 UTC
Labels: bug
